name: Build and Deploy rabbitmq to Development

on:
  push:
    branches-ignore:
      - main  

  pull_request:
    branches:
      - develop

  workflow_dispatch:

jobs:
  deploy:
    uses: robot-shop-DevOps/robot-shop-github-actions/.github/workflows/message-brokers.yaml@main
    with:
      IMAGE: rabbitmq
      NAMESPACE: rabbitmq
      RELEASE: rabbitmq
      DOCKERFILE_PATH: ./rabbitmq
    secrets: inherit